"""empty message

Revision ID: 13a5889df13
Revises: 9969fdf8fc9
Create Date: 2016-03-07 16:57:10.806493

"""

# revision identifiers, used by Alembic.
revision = '13a5889df13'
down_revision = '9969fdf8fc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('remark', sa.String(length=500), nullable=True))
    op.add_column('credit_apply', sa.Column('remark_img', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'remark_img')
    op.drop_column('credit_apply', 'remark')
    ### end Alembic commands ###
