"""empty message

Revision ID: 17354ab277c6
Revises: 1a31cb75f567
Create Date: 2015-12-18 22:43:45.517134

"""

# revision identifiers, used by Alembic.
revision = '17354ab277c6'
down_revision = '1a31cb75f567'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_code_user', sa.Column('lnglat', sa.String(length=100), nullable=True))
    op.add_column('qr_code_user', sa.Column('location', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_code_user', 'location')
    op.drop_column('qr_code_user', 'lnglat')
    ### end Alembic commands ###
