"""empty message

Revision ID: 18e20ed0da8d
Revises: 35c5bd051538
Create Date: 2016-02-05 10:42:00.617370

"""

# revision identifiers, used by Alembic.
revision = '18e20ed0da8d'
down_revision = '35c5bd051538'

from alembic import op
import sqlalchemy as sa
import models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redpack_user_question', sa.Column('money', models.MoneyField(precision=10, scale=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redpack_user_question', 'money')
    ### end Alembic commands ###
