"""empty message

Revision ID: 19af1cb7edf0
Revises: 5adc2c5e2c4f
Create Date: 2016-03-03 16:30:05.662503

"""

# revision identifiers, used by Alembic.
revision = '19af1cb7edf0'
down_revision = '5adc2c5e2c4f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rd_money_prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('sent', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rd_money_prize')
    ### end Alembic commands ###
