"""empty message

Revision ID: 1a31cb75f567
Revises: 4161c03ed1e6
Create Date: 2015-12-18 10:49:26.210775

"""

# revision identifiers, used by Alembic.
revision = '1a31cb75f567'
down_revision = '4161c03ed1e6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_reg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_reg')
    ### end Alembic commands ###
