"""empty message

Revision ID: 27acfdb5a809
Revises: 4ba5a6eafa93
Create Date: 2015-11-02 14:40:28.652562

"""

# revision identifiers, used by Alembic.
revision = '27acfdb5a809'
down_revision = '4ba5a6eafa93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_user', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospital_user', 'hospital', ['hospital_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospital_user', type_='foreignkey')
    op.drop_column('hospital_user', 'hospital_id')
    ### end Alembic commands ###
