"""empty message

Revision ID: 2b3331ab4b9d
Revises: f1412ee78a9
Create Date: 2015-12-05 10:28:51.755265

"""

# revision identifiers, used by Alembic.
revision = '2b3331ab4b9d'
down_revision = 'f1412ee78a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('passwd', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=False),
    sa.ForeignKeyConstraint(['create_by'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promoter')
    ### end Alembic commands ###
