"""empty message

Revision ID: 2c01f9e048f7
Revises: 34a907573645
Create Date: 2015-11-06 09:49:11.763111

"""

# revision identifiers, used by Alembic.
revision = '2c01f9e048f7'
down_revision = '34a907573645'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('help_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['help_cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_entry')
    op.drop_table('help_cat')
    ### end Alembic commands ###
