"""empty message

Revision ID: 31291b2ba259
Revises: 11926d4d1d71
Create Date: 2016-01-25 15:00:51.869707

"""

# revision identifiers, used by Alembic.
revision = '31291b2ba259'
down_revision = '11926d4d1d71'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_cat', sa.Column('sort_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_cat', 'sort_order')
    ### end Alembic commands ###
