"""empty message

Revision ID: 325324d21171
Revises: 166f1199e278
Create Date: 2015-12-05 14:28:37.978474

"""

# revision identifiers, used by Alembic.
revision = '325324d21171'
down_revision = '166f1199e278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promoter', sa.Column('name', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promoter', 'name')
    ### end Alembic commands ###
