"""empty message

Revision ID: 33a1596e092f
Revises: 2c06aa19dd1a
Create Date: 2015-11-26 14:02:10.367734

"""

# revision identifiers, used by Alembic.
revision = '33a1596e092f'
down_revision = '2c06aa19dd1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_item', sa.Column('image', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_item', 'image')
    ### end Alembic commands ###
