"""empty message

Revision ID: 34a7370fe40
Revises: 273db5f3044f
Create Date: 2016-02-01 14:55:03.924475

"""

# revision identifiers, used by Alembic.
revision = '34a7370fe40'
down_revision = '273db5f3044f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redpack_user_question', sa.Column('view_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redpack_user_question', 'view_count')
    ### end Alembic commands ###
