"""empty message

Revision ID: 3ae16db9c83e
Revises: 3d0882a6044
Create Date: 2016-01-27 15:03:50.881072

"""

# revision identifiers, used by Alembic.
revision = '3ae16db9c83e'
down_revision = '3d0882a6044'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ''' '''
    #foreign key constriant del order @xianpeng
    op.drop_constraint(u'room_design_detail_ibfk_1', 'room_design_detail', type_='foreignkey')
    op.drop_constraint(u'room_design_vote_log_ibfk_1', 'room_design_vote_log', type_='foreignkey')
    op.drop_column('room_design_detail', 'room_id')
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_design_apply')
    op.add_column('room_design_detail', sa.Column('applyer_name', sa.String(length=30), nullable=True))
    op.add_column('room_design_detail', sa.Column('room_name', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'room_design_detail', ['room_name'])
    op.create_foreign_key(None, 'room_design_vote_log', 'room_design_detail', ['room_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_design_vote_log', type_='foreignkey')
    op.create_foreign_key(u'room_design_vote_log_ibfk_1', 'room_design_vote_log', 'room_design_apply', ['room_id'], ['id'])
    op.add_column('room_design_detail', sa.Column('room_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'room_design_detail_ibfk_1', 'room_design_detail', 'room_design_apply', ['room_id'], ['id'])
    op.drop_constraint(None, 'room_design_detail', type_='unique')
    op.drop_column('room_design_detail', 'room_name')
    op.drop_column('room_design_detail', 'applyer_name')
    op.create_table('room_design_apply',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('school_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('room_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('applyer_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('addr', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], [u'school.id'], name=u'room_design_apply_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'room_design_apply_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
