"""empty message

Revision ID: 3c12ca43b1ba
Revises: 57366d94ca9a
Create Date: 2015-12-30 16:15:19.929785

"""

# revision identifiers, used by Alembic.
revision = '3c12ca43b1ba'
down_revision = '57366d94ca9a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('status', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'status')
    ### end Alembic commands ###
