"""empty message

Revision ID: 3c990682c3f0
Revises: 18e507e87862
Create Date: 2016-01-04 15:42:28.125990

"""

# revision identifiers, used by Alembic.
revision = '3c990682c3f0'
down_revision = '18e507e87862'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_coupon', sa.Column('use_condition', sa.String(length=100), nullable=True))
    op.add_column('daily_coupon', sa.Column('use_time', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_coupon', 'use_time')
    op.drop_column('daily_coupon', 'use_condition')
    ### end Alembic commands ###
