"""empty message

Revision ID: 3d1f1303d3e0
Revises: 37878b76721
Create Date: 2016-03-03 09:31:04.874943

"""

# revision identifiers, used by Alembic.
revision = '3d1f1303d3e0'
down_revision = '37878b76721'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rd_qrcode_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('qrcode_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qrcode_id'], ['qrcode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rd_user_qrcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('qrcode_id', sa.Integer(), nullable=True),
    sa.Column('follow_count', sa.Integer(), nullable=True),
    sa.Column('reg_count', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['qrcode_id'], ['qrcode.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'qrcode_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rd_user_qrcode')
    op.drop_table('rd_qrcode_user')
    ### end Alembic commands ###
