"""empty message

Revision ID: 3d20dc8132b4
Revises: 4e224649d340
Create Date: 2015-12-09 16:02:14.572280

"""

# revision identifiers, used by Alembic.
revision = '3d20dc8132b4'
down_revision = '4e224649d340'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trial_apply', ['user_id', 'trial_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trial_apply', type_='unique')
    ### end Alembic commands ###
