"""empty message

Revision ID: 3ecdf504db70
Revises: 1cf4dd01482b
Create Date: 2015-11-11 10:13:33.887260

"""

# revision identifiers, used by Alembic.
revision = '3ecdf504db70'
down_revision = '1cf4dd01482b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend_subcat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_cat_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['item_sub_cat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_cat_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommend_subcat')
    ### end Alembic commands ###
