"""empty message

Revision ID: 3f2769d4ed16
Revises: 48dc9132c95d
Create Date: 2016-01-07 14:45:40.525524

"""

# revision identifiers, used by Alembic.
revision = '3f2769d4ed16'
down_revision = '48dc9132c95d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beauty_entry', sa.Column('items', sa.String(length=100), nullable=True))
    op.add_column('beauty_entry', sa.Column('photo', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beauty_entry', 'photo')
    op.drop_column('beauty_entry', 'items')
    ### end Alembic commands ###
