"""empty message

Revision ID: 4161c03ed1e6
Revises: 2eb48ce629a0
Create Date: 2015-12-17 19:35:22.464397

"""

# revision identifiers, used by Alembic.
revision = '4161c03ed1e6'
down_revision = '2eb48ce629a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_code_user', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('qr_code_user', sa.Column('headimgurl', sa.String(length=300), nullable=True))
    op.add_column('qr_code_user', sa.Column('nickname', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_code_user', 'nickname')
    op.drop_column('qr_code_user', 'headimgurl')
    op.drop_column('qr_code_user', 'city')
    ### end Alembic commands ###
