"""empty message

Revision ID: 41e40e694b32
Revises: 92d3f0175a1
Create Date: 2015-11-27 14:25:08.574706

"""

# revision identifiers, used by Alembic.
revision = '41e40e694b32'
down_revision = '92d3f0175a1'

from alembic import op
import sqlalchemy as sa
import models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_log_order_no',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=30), nullable=True),
    sa.Column('period_pay_log_id', sa.Integer(), nullable=True),
    sa.Column('price', models.MoneyField(precision=10, scale=2), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['period_pay_log_id'], ['period_pay_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_pay_log_id')
    )
    op.create_index(op.f('ix_pay_log_order_no_order_no'), 'pay_log_order_no', ['order_no'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_log_order_no_order_no'), table_name='pay_log_order_no')
    op.drop_table('pay_log_order_no')
    ### end Alembic commands ###
