"""empty message

Revision ID: 4cf4f86adc0c
Revises: 3ecdf504db70
Create Date: 2015-11-11 11:44:50.579661

"""

# revision identifiers, used by Alembic.
revision = '4cf4f86adc0c'
down_revision = '3ecdf504db70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommend_item', sa.Column('desc', sa.String(length=500), nullable=True))
    op.add_column('recommend_item', sa.Column('image', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommend_item', 'image')
    op.drop_column('recommend_item', 'desc')
    ### end Alembic commands ###
