"""empty message

Revision ID: 4d043b343761
Revises: 3355a78241bf
Create Date: 2015-12-08 20:25:50.997862

"""

# revision identifiers, used by Alembic.
revision = '4d043b343761'
down_revision = '3355a78241bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fake_user')
    ### end Alembic commands ###
