"""empty message

Revision ID: 4f4ce8bff86a
Revises: 11da3b568bd2
Create Date: 2016-01-09 17:18:22.196431

"""

# revision identifiers, used by Alembic.
revision = '4f4ce8bff86a'
down_revision = '11da3b568bd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beauty_entry', sa.Column('view_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beauty_entry', 'view_count')
    ### end Alembic commands ###
