"""empty message

Revision ID: 51187e1e4dbc
Revises: 51aaf1e0ecdd
Create Date: 2015-11-16 10:27:52.435910

"""

# revision identifiers, used by Alembic.
revision = '51187e1e4dbc'
down_revision = '51aaf1e0ecdd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('photos', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'photos')
    ### end Alembic commands ###
