"""empty message

Revision ID: 5329d119ee5f
Revises: 125c0c0cb424
Create Date: 2015-11-04 10:52:05.593655

"""

# revision identifiers, used by Alembic.
revision = '5329d119ee5f'
down_revision = '125c0c0cb424'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_recommend', sa.Boolean(), nullable=True))
    op.add_column('item', sa.Column('status', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'status')
    op.drop_column('item', 'is_recommend')
    ### end Alembic commands ###
