"""empty message

Revision ID: 569e3d7f70ab
Revises: 5784ac6510c3
Create Date: 2015-12-10 10:39:57.648906

"""

# revision identifiers, used by Alembic.
revision = '569e3d7f70ab'
down_revision = '5784ac6510c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('sub_cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coupon', 'item_sub_cat', ['sub_cat_id'], ['id'])
    op.add_column('user_coupon', sa.Column('sub_cat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_coupon', 'item_sub_cat', ['sub_cat_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_coupon', type_='foreignkey')
    op.drop_column('user_coupon', 'sub_cat_id')
    op.drop_constraint(None, 'coupon', type_='foreignkey')
    op.drop_column('coupon', 'sub_cat_id')
    ### end Alembic commands ###
