"""empty message

Revision ID: 59a610b5633d
Revises: 3a64535997fb
Create Date: 2015-12-09 17:16:46.162195

"""

# revision identifiers, used by Alembic.
revision = '59a610b5633d'
down_revision = '3a64535997fb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial', sa.Column('sex', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial', 'sex')
    ### end Alembic commands ###
