"""empty message

Revision ID: 75f96105f81
Revises: 41e40e694b32
Create Date: 2015-11-27 15:04:57.429923

"""

# revision identifiers, used by Alembic.
revision = '75f96105f81'
down_revision = '41e40e694b32'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repayment', 'data')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayment', sa.Column('data', mysql.VARCHAR(length=1000), nullable=True))
    ### end Alembic commands ###
