"""empty message

Revision ID: 765d6f2d606
Revises: 4bd7029c14b5
Create Date: 2015-11-20 14:50:33.668652

"""

# revision identifiers, used by Alembic.
revision = '765d6f2d606'
down_revision = '4bd7029c14b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hospital', 'city', ['city_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hospital', type_='foreignkey')
    op.drop_column('hospital', 'city_id')
    ### end Alembic commands ###
