"""empty message

Revision ID: 9969fdf8fc9
Revises: 1b538e70897
Create Date: 2016-03-07 16:32:03.339046

"""

# revision identifiers, used by Alembic.
revision = '9969fdf8fc9'
down_revision = '1b538e70897'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('remark', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'remark')
    ### end Alembic commands ###
