"""empty message

Revision ID: c855246d7e8
Revises: 1bef4d9bd99b
Create Date: 2015-11-03 10:38:03.675764

"""

# revision identifiers, used by Alembic.
revision = 'c855246d7e8'
down_revision = '1bef4d9bd99b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('reason', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'reason')
    ### end Alembic commands ###
