"""empty message

Revision ID: f1412ee78a9
Revises: 46669801ed5f
Create Date: 2015-12-04 16:35:33.875597

"""

# revision identifiers, used by Alembic.
revision = 'f1412ee78a9'
down_revision = '46669801ed5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    ### end Alembic commands ###
