"""empty message

Revision ID: 15e92c9ccee8
Revises: 45f8da7eae76
Create Date: 2015-12-12 15:36:09.053853

"""

# revision identifiers, used by Alembic.
revision = '15e92c9ccee8'
down_revision = '45f8da7eae76'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial', sa.Column('process', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial', 'process')
    ### end Alembic commands ###
