"""empty message

Revision ID: 166f1199e278
Revises: 2b3331ab4b9d
Create Date: 2015-12-05 10:39:03.429532

"""

# revision identifiers, used by Alembic.
revision = '166f1199e278'
down_revision = '2b3331ab4b9d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promoter_qrcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=100), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promoter_qrcode_scene_id'), 'promoter_qrcode', ['scene_id'], unique=False)
    op.create_table('qrcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket', sa.String(length=100), nullable=True),
    sa.Column('promoter_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['promoter_id'], ['promoter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qrcode')
    op.drop_index(op.f('ix_promoter_qrcode_scene_id'), table_name='promoter_qrcode')
    op.drop_table('promoter_qrcode')
    ### end Alembic commands ###
