"""empty message

Revision ID: 1cf4dd01482b
Revises: 32a72ba0ce03
Create Date: 2015-11-10 11:09:59.892332

"""

# revision identifiers, used by Alembic.
revision = '1cf4dd01482b'
down_revision = '32a72ba0ce03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommend_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.drop_column(u'item', 'is_recommend')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'item', sa.Column('is_recommend', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('recommend_item')
    ### end Alembic commands ###
