"""empty message

Revision ID: 200344fc698d
Revises: 3ae16db9c83e
Create Date: 2016-01-27 15:15:16.187355

"""

# revision identifiers, used by Alembic.
revision = '200344fc698d'
down_revision = '3ae16db9c83e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('phone', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_design_detail', 'phone')
    ### end Alembic commands ###
