"""empty message

Revision ID: 21e38b1473b2
Revises: 2c01f9e048f7
Create Date: 2015-11-07 14:35:55.667526

"""

# revision identifiers, used by Alembic.
revision = '21e38b1473b2'
down_revision = '2c01f9e048f7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('refund', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'refund')
    ### end Alembic commands ###
