"""empty message

Revision ID: 2550693fdc3a
Revises: 3642e05a5117
Create Date: 2015-12-28 14:58:03.723465

"""

# revision identifiers, used by Alembic.
revision = '2550693fdc3a'
down_revision = '3642e05a5117'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sub_cat_ids', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'sub_cat_ids')
    ### end Alembic commands ###
