"""empty message

Revision ID: 2a01c5929823
Revises: 285c9a12f7b4
Create Date: 2016-01-27 15:32:02.925482

"""

# revision identifiers, used by Alembic.
revision = '2a01c5929823'
down_revision = '285c9a12f7b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('phone', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'room_design_detail', ['phone'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_design_detail', type_='unique')
    op.drop_column('room_design_detail', 'phone')
    ### end Alembic commands ###
