"""empty message

Revision ID: 2ab4005efb6c
Revises: 2a01c5929823
Create Date: 2016-01-27 16:01:27.623336

"""

# revision identifiers, used by Alembic.
revision = '2ab4005efb6c'
down_revision = '2a01c5929823'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('addr', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_design_detail', 'addr')
    ### end Alembic commands ###
