"""empty message

Revision ID: 2b097c44cbba
Revises: 4806ede530e3
Create Date: 2015-11-24 10:03:17.516996

"""

# revision identifiers, used by Alembic.
revision = '2b097c44cbba'
down_revision = '4806ede530e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_finished', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'user_finished')
    ### end Alembic commands ###
