"""empty message

Revision ID: 2eed88b994ed
Revises: 3621ae6c4339
Create Date: 2015-10-31 10:12:42.506018

"""

# revision identifiers, used by Alembic.
revision = '2eed88b994ed'
down_revision = '3621ae6c4339'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayment', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.add_column('repayment', sa.Column('pay_method', mysql.TINYINT(display_width=1), nullable=False))
    op.create_unique_constraint(None, 'repayment', ['coupon_id'])
    op.create_foreign_key(None, 'repayment', 'user_coupon', ['coupon_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repayment', type_='foreignkey')
    op.drop_constraint(None, 'repayment', type_='unique')
    op.drop_column('repayment', 'pay_method')
    op.drop_column('repayment', 'coupon_id')
    ### end Alembic commands ###
