"""empty message

Revision ID: 32ca0414826f
Revises: 29bbb2cfc971
Create Date: 2016-01-28 11:49:27.884628

"""

# revision identifiers, used by Alembic.
revision = '32ca0414826f'
down_revision = '29bbb2cfc971'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_design_vote_log', 'vote_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_vote_log', sa.Column('vote_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
