"""empty message

Revision ID: 3355a78241bf
Revises: 4ba650ba661f
Create Date: 2015-12-07 14:33:58.967971

"""

# revision identifiers, used by Alembic.
revision = '3355a78241bf'
down_revision = '4ba650ba661f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promoter_qrcode')
    op.add_column('qrcode', sa.Column('act_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qrcode', 'act_type')
    op.create_table('promoter_qrcode',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ticket', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('promoter_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('qrcode_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['promoter_id'], [u'promoter.id'], name=u'promoter_qrcode_ibfk_1'),
    sa.ForeignKeyConstraint(['qrcode_id'], [u'qrcode.id'], name=u'promoter_qrcode_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
