"""empty message

Revision ID: 348398960582
Revises: 5329d119ee5f
Create Date: 2015-11-05 11:06:06.364444

"""

# revision identifiers, used by Alembic.
revision = '348398960582'
down_revision = '5329d119ee5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'transaction_id')
    ### end Alembic commands ###
