"""empty message

Revision ID: 34a907573645
Revises: 348398960582
Create Date: 2015-11-05 11:12:57.759917

"""

# revision identifiers, used by Alembic.
revision = '34a907573645'
down_revision = '348398960582'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayment', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repayment', 'transaction_id')
    ### end Alembic commands ###
