"""empty message

Revision ID: 36d5b6be1479
Revises: 4a4cc4517bb
Create Date: 2015-11-11 16:43:11.679555

"""

# revision identifiers, used by Alembic.
revision = '36d5b6be1479'
down_revision = '4a4cc4517bb'

from alembic import op
import sqlalchemy as sa

import models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_item', sa.Column('price', models.MoneyField(precision=10, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_item', 'price')
    ### end Alembic commands ###
