"""empty message

Revision ID: 37321f4a22b3
Revises: 4deed7860ffe
Create Date: 2015-12-20 09:45:00.700298

"""

# revision identifiers, used by Alembic.
revision = '37321f4a22b3'
down_revision = '4deed7860ffe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('has_supply', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'has_supply')
    ### end Alembic commands ###
