"""empty message

Revision ID: 3a64535997fb
Revises: 3d20dc8132b4
Create Date: 2015-12-09 16:06:25.045848

"""

# revision identifiers, used by Alembic.
revision = '3a64535997fb'
down_revision = '3d20dc8132b4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'trial_ibfk_2', 'trial', type_='foreignkey')
    op.drop_column('trial', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'trial_ibfk_2', 'trial', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
