"""empty message

Revision ID: 3c706c57fa0
Revises: 2ce138017f09
Create Date: 2015-12-11 16:07:38.421306

"""

# revision identifiers, used by Alembic.
revision = '3c706c57fa0'
down_revision = '2ce138017f09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'trial_apply_ibfk_3', 'trial_apply', type_='foreignkey')
    op.create_foreign_key(None, 'trial_apply', 'user_coupon', ['coupon_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trial_apply', type_='foreignkey')
    op.create_foreign_key(u'trial_apply_ibfk_3', 'trial_apply', 'coupon', ['coupon_id'], ['id'])
    ### end Alembic commands ###
