"""empty message

Revision ID: 3ee27e625d6d
Revises: 43f0dd6800b1
Create Date: 2015-11-17 14:53:58.824350

"""

# revision identifiers, used by Alembic.
revision = '3ee27e625d6d'
down_revision = '43f0dd6800b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('stu_education', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'stu_education')
    ### end Alembic commands ###
