"""empty message

Revision ID: 43f0dd6800b1
Revises: 4c9fdc97c246
Create Date: 2015-11-17 14:11:31.124384

"""

# revision identifiers, used by Alembic.
revision = '43f0dd6800b1'
down_revision = '4c9fdc97c246'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('direct_buy', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'direct_buy')
    ### end Alembic commands ###
