"""empty message

Revision ID: 480dd7e7caac
Revises: 59a610b5633d
Create Date: 2015-12-09 17:20:34.481073

"""

# revision identifiers, used by Alembic.
revision = '480dd7e7caac'
down_revision = '59a610b5633d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial', 'sex')
    op.add_column('trial_apply', sa.Column('sex', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial_apply', 'sex')
    op.add_column('trial', sa.Column('sex', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    ### end Alembic commands ###
