"""empty message

Revision ID: 4a4cc4517bb
Revises: 4cf4f86adc0c
Create Date: 2015-11-11 14:04:48.035474

"""

# revision identifiers, used by Alembic.
revision = '4a4cc4517bb'
down_revision = '4cf4f86adc0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_item', sa.Column('sort_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_item', 'sort_order')
    ### end Alembic commands ###
