"""empty message

Revision ID: 4bd7029c14b5
Revises: 3ee27e625d6d
Create Date: 2015-11-19 18:10:40.370035

"""

# revision identifiers, used by Alembic.
revision = '4bd7029c14b5'
down_revision = '3ee27e625d6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('create_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'create_time')
    ### end Alembic commands ###
