"""empty message

Revision ID: 4be704e34845
Revises: 325324d21171
Create Date: 2015-12-05 14:34:06.582315

"""

# revision identifiers, used by Alembic.
revision = '4be704e34845'
down_revision = '325324d21171'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promoter', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promoter', 'create_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
