"""empty message

Revision ID: 4c9fdc97c246
Revises: 51187e1e4dbc
Create Date: 2015-11-16 11:05:15.297821

"""

# revision identifiers, used by Alembic.
revision = '4c9fdc97c246'
down_revision = '51187e1e4dbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    ### end Alembic commands ###
