"""empty message

Revision ID: 4eefa5b6eb51
Revises: 55f4c256c989
Create Date: 2015-11-28 10:09:38.336732

"""

# revision identifiers, used by Alembic.
revision = '4eefa5b6eb51'
down_revision = '55f4c256c989'

from alembic import op
import sqlalchemy as sa
import models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_log_order_no', sa.Column('total', models.MoneyField(precision=10, scale=2), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay_log_order_no', 'total')
    ### end Alembic commands ###
