"""empty message

Revision ID: 503198b95377
Revises: 765d6f2d606
Create Date: 2015-11-22 19:55:58.240016

"""

# revision identifiers, used by Alembic.
revision = '503198b95377'
down_revision = '765d6f2d606'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_comment', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_comment', 'order', ['order_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_comment', type_='foreignkey')
    op.drop_column('item_comment', 'order_id')
    ### end Alembic commands ###
