"""empty message

Revision ID: 54d0e0d4445b
Revises: 4f4ce8bff86a
Create Date: 2016-01-11 15:39:22.872865

"""

# revision identifiers, used by Alembic.
revision = '54d0e0d4445b'
down_revision = '4f4ce8bff86a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('amap_code', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'city', ['amap_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_column('city', 'amap_code')
    ### end Alembic commands ###
