"""empty message

Revision ID: 5853d4187f15
Revises: 3f2769d4ed16
Create Date: 2016-01-07 15:41:09.540410

"""

# revision identifiers, used by Alembic.
revision = '5853d4187f15'
down_revision = '3f2769d4ed16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_sub_cat', sa.Column('cat_ids', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_sub_cat', 'cat_ids')
    ### end Alembic commands ###
