"""empty message

Revision ID: 92d3f0175a1
Revises: 33a1596e092f
Create Date: 2015-11-26 17:26:27.429010

"""

# revision identifiers, used by Alembic.
revision = '92d3f0175a1'
down_revision = '33a1596e092f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('city_code', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'city', ['city_code'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_column('city', 'city_code')
    ### end Alembic commands ###
