"""empty message

Revision ID: d5045d5ecf4
Revises: 1c198b1a91cb
Create Date: 2015-12-15 16:51:04.837716

"""

# revision identifiers, used by Alembic.
revision = 'd5045d5ecf4'
down_revision = '1c198b1a91cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial', sa.Column('sort_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial', 'sort_order')
    ### end Alembic commands ###
