"""empty message

Revision ID: 10f3ed6c72ed
Revises: 75f96105f81
Create Date: 2015-11-27 15:05:27.624606

"""

# revision identifiers, used by Alembic.
revision = '10f3ed6c72ed'
down_revision = '75f96105f81'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repayment', sa.Column('data', sa.String(length=10000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repayment', 'data')
    ### end Alembic commands ###
