"""empty message

Revision ID: 11926d4d1d71
Revises: 2ea902b5c7a3
Create Date: 2016-01-14 20:23:45.259966

"""

# revision identifiers, used by Alembic.
revision = '11926d4d1d71'
down_revision = '2ea902b5c7a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_coupon', sa.Column('title', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_coupon', 'title')
    ### end Alembic commands ###
