"""empty message

Revision ID: 125c0c0cb424
Revises: c855246d7e8
Create Date: 2015-11-03 11:42:59.684984

"""

# revision identifiers, used by Alembic.
revision = '125c0c0cb424'
down_revision = 'c855246d7e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('graduate_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'graduate_time')
    ### end Alembic commands ###
