"""empty message

Revision ID: 285c9a12f7b4
Revises: 200344fc698d
Create Date: 2016-01-27 15:31:26.017505

"""

# revision identifiers, used by Alembic.
revision = '285c9a12f7b4'
down_revision = '200344fc698d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_design_detail', 'phone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('phone', mysql.VARCHAR(length=30), nullable=True))
    ### end Alembic commands ###
