"""empty message

Revision ID: 29347d4f2522
Revises: 2ab4005efb6c
Create Date: 2016-01-27 17:27:42.642697

"""

# revision identifiers, used by Alembic.
revision = '29347d4f2522'
down_revision = '2ab4005efb6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('apply_no', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'room_design_detail', ['apply_no'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_design_detail', type_='unique')
    op.drop_column('room_design_detail', 'apply_no')
    ### end Alembic commands ###
