"""empty message

Revision ID: 2c06aa19dd1a
Revises: 2b097c44cbba
Create Date: 2015-11-24 11:09:16.149962

"""

# revision identifiers, used by Alembic.
revision = '2c06aa19dd1a'
down_revision = '2b097c44cbba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_name_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edit_name_log')
    ### end Alembic commands ###
