"""empty message

Revision ID: 2d7888ae13f9
Revises: 2550693fdc3a
Create Date: 2015-12-30 15:08:53.742555

"""

# revision identifiers, used by Alembic.
revision = '2d7888ae13f9'
down_revision = '2550693fdc3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('image', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'image')
    ### end Alembic commands ###
