"""empty message

Revision ID: 2eb48ce629a0
Revises: d5045d5ecf4
Create Date: 2015-12-16 15:59:24.978212

"""

# revision identifiers, used by Alembic.
revision = '2eb48ce629a0'
down_revision = 'd5045d5ecf4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_size',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_size')
    ### end Alembic commands ###
