"""empty message

Revision ID: 3107ca470fdf
Revises: 57be38c1806e
Create Date: 2016-02-26 15:45:09.438185

"""

# revision identifiers, used by Alembic.
revision = '3107ca470fdf'
down_revision = '57be38c1806e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_design_detail', sa.Column('pics_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_room_design_detail_pics_count'), 'room_design_detail', ['pics_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_design_detail_pics_count'), table_name='room_design_detail')
    op.drop_column('room_design_detail', 'pics_count')
    ### end Alembic commands ###
