"""empty message

Revision ID: 314740bf50b9
Revises: fe9b95bfea6
Create Date: 2015-11-29 12:14:02.763748

"""

# revision identifiers, used by Alembic.
revision = '314740bf50b9'
down_revision = 'fe9b95bfea6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_use_log', sa.Column('status', mysql.TINYINT(display_width=1), nullable=False))
    op.drop_column('credit_use_log', 'cat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_use_log', sa.Column('cat', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('credit_use_log', 'status')
    ### end Alembic commands ###
