"""empty message

Revision ID: 345ee23bca8
Revises: 480dd7e7caac
Create Date: 2015-12-09 17:48:46.918282

"""

# revision identifiers, used by Alembic.
revision = '345ee23bca8'
down_revision = '480dd7e7caac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trial_apply', sa.Column('status', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trial_apply', 'status')
    ### end Alembic commands ###
