"""empty message

Revision ID: 3642e05a5117
Revises: 37321f4a22b3
Create Date: 2015-12-25 14:40:56.163993

"""

# revision identifiers, used by Alembic.
revision = '3642e05a5117'
down_revision = '37321f4a22b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promoter', sa.Column('dup_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_promoter_dup_count'), 'promoter', ['dup_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promoter_dup_count'), table_name='promoter')
    op.drop_column('promoter', 'dup_count')
    ### end Alembic commands ###
