"""empty message

Revision ID: 37878b76721
Revises: 3107ca470fdf
Create Date: 2016-02-27 10:16:36.087236

"""

# revision identifiers, used by Alembic.
revision = '37878b76721'
down_revision = '3107ca470fdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('pics_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_school_pics_count'), 'school', ['pics_count'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_pics_count'), table_name='school')
    op.drop_column('school', 'pics_count')
    ### end Alembic commands ###
