"""empty message

Revision ID: 42d4367e28b2
Revises: 569e3d7f70ab
Create Date: 2015-12-10 10:58:36.611750

"""

# revision identifiers, used by Alembic.
revision = '42d4367e28b2'
down_revision = '569e3d7f70ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('title', sa.String(length=300), nullable=True))
    op.add_column('user_coupon', sa.Column('title', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_coupon', 'title')
    op.drop_column('coupon', 'title')
    ### end Alembic commands ###
