"""empty message

Revision ID: 46669801ed5f
Revises: 314740bf50b9
Create Date: 2015-12-04 15:39:42.974215

"""

# revision identifiers, used by Alembic.
revision = '46669801ed5f'
down_revision = '314740bf50b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_code_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=50), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('open_id')
    )
    op.create_index(op.f('ix_qr_code_user_scene_id'), 'qr_code_user', ['scene_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_code_user_scene_id'), table_name='qr_code_user')
    op.drop_table('qr_code_user')
    ### end Alembic commands ###
