"""empty message

Revision ID: 48dc9132c95d
Revises: 492dcdfca828
Create Date: 2016-01-06 14:09:01.813368

"""

# revision identifiers, used by Alembic.
revision = '48dc9132c95d'
down_revision = '492dcdfca828'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beauty_entry', sa.Column('status', mysql.TINYINT(display_width=1), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beauty_entry', 'status')
    ### end Alembic commands ###
