"""empty message

Revision ID: 53a9d06e37ce
Revises: 2eed88b994ed
Create Date: 2015-10-31 14:18:39.072291

"""

# revision identifiers, used by Alembic.
revision = '53a9d06e37ce'
down_revision = '2eed88b994ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'item_no')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_no', mysql.VARCHAR(length=50), nullable=True))
    ### end Alembic commands ###
