"""empty message

Revision ID: 57366d94ca9a
Revises: 2d7888ae13f9
Create Date: 2015-12-30 15:30:29.964102

"""

# revision identifiers, used by Alembic.
revision = '57366d94ca9a'
down_revision = '2d7888ae13f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('rate', sa.Float(), nullable=True))
    op.add_column('hospital', sa.Column('sold_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'sold_count')
    op.drop_column('hospital', 'rate')
    ### end Alembic commands ###
