"""empty message

Revision ID: 57be38c1806e
Revises: 6a2ac421f56
Create Date: 2016-02-24 16:41:00.918666

"""

# revision identifiers, used by Alembic.
revision = '57be38c1806e'
down_revision = '6a2ac421f56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_apply', sa.Column('body_choice_ids', sa.String(length=100), nullable=True))
    op.add_column('credit_apply', sa.Column('body_choice_text', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_apply', 'body_choice_text')
    op.drop_column('credit_apply', 'body_choice_ids')
    ### end Alembic commands ###
