"""empty message

Revision ID: 58261a151f1d
Revises: 27acfdb5a809
Create Date: 2015-11-02 16:22:37.840559

"""

# revision identifiers, used by Alembic.
revision = '58261a151f1d'
down_revision = '27acfdb5a809'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order', 'hospital', ['hospital_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'hospital_id')
    ### end Alembic commands ###
