"""empty message

Revision ID: e1bfa676445
Revises: 21e38b1473b2
Create Date: 2015-11-07 16:08:03.127777

"""

# revision identifiers, used by Alembic.
revision = 'e1bfa676445'
down_revision = '21e38b1473b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('doctor_desc', sa.Text(), nullable=True))
    op.add_column('item', sa.Column('surgery_desc', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'surgery_desc')
    op.drop_column('item', 'doctor_desc')
    ### end Alembic commands ###
